//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineersMatrimony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_Profile
    {
        public Nullable<int> MID { get; set; }
        public System.DateTime DOB { get; set; }
        public string District { get; set; }
        public string Photo1 { get; set; }
    }
}
