//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineersMatrimony.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EngineersMatrimonyEntities : DbContext
    {
        public EngineersMatrimonyEntities()
            : base("name=EngineersMatrimonyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Basic_Profile> Basic_Profile { get; set; }
    }
}
