//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineersMatrimony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int PrefID { get; set; }
        public Nullable<int> MID { get; set; }
        public int AgeFrom { get; set; }
        public int AgeTo { get; set; }
        public double HeightFrom { get; set; }
        public double HeightTo { get; set; }
        public double WeightFrom { get; set; }
        public double WeightTo { get; set; }
        public string Job { get; set; }
        public string MaritalStatus { get; set; }
        public string FamilyType { get; set; }
        public Nullable<double> IncomeFrom { get; set; }
        public Nullable<double> IncomeTo { get; set; }
        public string District { get; set; }
        public string Gender { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
